= Deckcards

Deckcards is a tool used to generate game's cards from a template and a Google Spreadsheet.

== Disclaimer

It's an early version that barely comes out of the furnace.
If you want to improve this project you can contribute by submitting https://github.com/mrpierrot/deckcards/issues[an issue] or propose a https://github.com/mrpierrot/deckcards/pulls[pull request]

Currently, works fine with nodeJS 6.9.1 and should work fine with nodeJS 6.4.0 and above.

PS: My English can be poor. If you see an incorrect sentence, please report it to me, I won't take it the wrong way :-)

== Install

Install with npm:

------
npm install deckcards -g
------

== Get started

=== Create a project

First, use this command to create a project with default content in the directory *"project_name"*:

------
deckcards setup <project_name>
------

Next, go to the directory *"project_name"*

------
cd ./<project_name>
------

The project contains the following files :

[options="header,footer"]
|===========================================
| File              | Description
| deckcards.json    | The configuration files
| template.html     | The HTML template file. Look at http://handlebarsjs.com/[Handlebars.js] to edit.
| styles.css        | The template's styles.
|===========================================  


=== deckcards.json

The default deckcards.json

[source, json]
------
{
    "template":"template.html",
    "output":"./cards",
    "gsheet":{
        "sheetId":"1QJm95kTdpR9XT6fC7sirsPRVFjOOri74-jH3mSd1gf8",
        "credentials":null
    }
}
------

==== Description

[options="header,footer"]
|============================================
| Name              | Description 
| template          | The HTML template path
| output            | The directory where final HTML files are generated
| gsheet.sheetId    | The Google Spreadsheet's ID. It can be found here:
docs.google.com/spreadsheets/d/*1QJm95kTdpR9XT6fC7sirsPRVFjOOri74-jH3mSd1gf8*/edit?usp=sharing
| gsheet.credentials | The credentials file path (i.e. *"./credentials.json"*). Set it to *null* if you use a public Google Spreadsheet.
|============================================

=== Configure Google authentication

For private and public Google Spreadsheets, follow the instructions from https://github.com/theoephraim/node-google-spreadsheet#authentication[node-google-spreadsheet]

If you use private Google Spreadsheet, you get a JSON file with credentials. Copy this file into the project directory and rename it *credentials.json*

In deckcards.json, define the credentials.json path like this:

[source, json]
------
{
    ...
    "gsheet":{
        ...
        "credentials":"./credentials.json"
    }
}
------

=== Google Spreadsheet Format

You can find an example https://docs.google.com/spreadsheets/d/1QJm95kTdpR9XT6fC7sirsPRVFjOOri74-jH3mSd1gf8/edit#gid=2092230795[here]

The first line contains the variable names (here: NAME and DESC) and the next lines store the values.

You can define several sheets, each of them generating its own HTML page.

=== License

Licensed under the link:LICENSE[MIT]
